### ISSUE TITLE
YML 문법 정리

### ISSUE THREAD

**Issue by iamabear09** [iamabear09/__STUDY__prometheus-grafana#4]
### 하이픈 `-` 배열 
배열 & 리스트를 표현하는데 사용된다.
```yaml
ingredients:
   - 닭
   - 튀김가루
   - 자바소스
```
```json
{
  "ingredients": [
    "닭",
    "튀김가루",
    "자바소스"
  ]
}
```
`[ ]`를 사용하여 배열 & 리스트 표현도 가능하다.
```
ingredients: [닭, 튀김가루, 자바소스]
```

### 하이픈 `-` 객체 배열

```
students:
  - name: Mark
    major: Math
    age: 20
  - name: Julie
    major: Arts
    age: 23
  - name: Tommy
    major: Music
    age: 25
```
```
{
  "students": [
    {
      "name": "Mark",
      "major": "Math",
      "age": 20
    },
    {
      "name": "Julie",
      "major": "Arts",
      "age": 23
    },
    {
      "name": "Tommy",
      "major": "Music",
      "age": 25
    }
  ]
}
```

참고 :: [yaml 문법 정리](https://inpa.tistory.com/entry/YAML-%F0%9F%93%9A-yaml-%EA%B0%9C%EB%85%90-%EB%AC%B8%EB%B2%95-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-%F0%9F%92%AF-%EC%B4%9D%EC%A0%95%EB%A6%AC#yaml_%EC%9D%B4%EB%9E%80?)
